---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-cache
  namespace: object-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi