---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: nginx-cache
  namespace: object-storage
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nginx"